### ISSUE TITLE
KeyError: 'x-csrf-token'

### ISSUE THREAD

**Issue by Birdy3000** [SAP-samples/analytics-cloud-export-api-wrapper#4]
Error: 
```
Traceback (most recent call last):
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/sacapi.py", line 215, in getProviders
    importCSRFToken = importResponse.headers._store["x-csrf-token"]
KeyError: 'x-csrf-token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/try_request_online.py", line 142, in <module>
    main()
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/try_request_online.py", line 8, in main
    v2_test()
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/try_request_online.py", line 24, in v2_test
    sac.connect(client_id, client_secret)
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/sacapi.py", line 440, in connect
    raise e
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/sacapi.py", line 434, in connect
    self.getProviders()
  File "/Users/schos/Desktop/02_azure/PythonSACApi/tests/sacapi.py", line 245, in getProviders
    if e.status_code:
AttributeError: 'KeyError' object has no attribute 'status_code'
```

with this code:

```
    sac = SACConnection(tenant, datacenter)
    sac.connect(client_id, client_secret)
    md = sac.getModelMetadata(model_technical_id)
    #    fd = sac.getFactData(md)

    print(fd)
```

What is the reason for this?

**Comment by davidhstocker** [comment]
Sorry about that.  The latest check ins include the import API.  What happened is that I switched from reading the catalog endpoint on the export API, to reading the catalog endpoint on the import API.  It is mostly the same, except that the import endpoint also returns a [CSRF Token](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#:~:text=CSRF%20tokens%20prevent%20CSRF%20because,a%20HTML%20or%20JSON%20response), which gets assed to the .  This is because there are a lot of POST operations on the import side, so we pick up the CSRF session token from the first GET endpoint and can use it in the POST endpoints later on.  The export endpoints are all GET and don't return a CSRF token, because it was not needed.

The import endpoints are in release 2023.QRC3, which is out next month.  It should work against a preview tenant, but I presume that you are trying this against a QRC tenant.  I'll fix it by catching this exception and falling back onto the export endpoint to read the catalog; hopefully today.

**Comment by davidhstocker** [comment]
Changelist [a6f5903](https://github.com/SAP-samples/analytics-cloud-export-api-wrapper/commit/a6f5903b50a0a4d012cca563ca6c7a10d0eaca76) should fix this.  Now, if it fails to connect to import/models, it will read from export/providers/sac instead and warn you that it was unable to acquire the csrf token.  It will also throw an exception afterwards, whenever you try to use the import methods.

It also posts a warning to the console.  On my tenant, it looks like:

> WARNING.  Failed to connect to https://appdesign.eu10.sapanalytics.cloud/api/v1/dataimport/models and fell back on https://appdesign.eu10.sapanalytics.cloud/api/v1/dataexport/providers/sac, to read the model catalog.  No CSRF token is available from this endpoint, so import operations will not be possible.

As soon as your tenant has import available and you have set up access in the app client configuration (2 legged OAuth access for import and export are two separate flags), import should work for you again.
